[__global__]
# Where the RHEL repo is (Option A: local mirror you rsynced)
repo=http://192.168.1.10/install
kernel=(http,192.168.1.10)/boot/vmlinuz
initrd=(http,192.168.1.10)/boot/initrd.img
ks_base=http://192.168.1.10/ks
# set to yes to auto-reset allowed=no after GRUB reads once
oneshot=yes

# Example profiles

[00:1a:2b:3c:4d:5e]
kickstart=webserver.cfg
allowed=no

[00:1a:2b:3c:4d:5f]
kickstart=database.cfg
allowed=no

[00:1a:2b:3c:4d:60]
kickstart=minimal.cfg
allowed=no

